// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: crypto_service.proto

package fr.gouv.stopc.robert.crypto.grpc.server.service;

public final class CryptoGrpcService {
    private CryptoGrpcService() {}
    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }
    public static final com.google.protobuf.Descriptors.Descriptor
    internal_static_robert_server_crypto_EphemeralTupleRequest_descriptor;
    public static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internal_static_robert_server_crypto_EphemeralTupleRequest_fieldAccessorTable;
    public static final com.google.protobuf.Descriptors.Descriptor
    internal_static_robert_server_crypto_EphemeralTupleResponse_descriptor;
    public static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internal_static_robert_server_crypto_EphemeralTupleResponse_fieldAccessorTable;
    public static final com.google.protobuf.Descriptors.Descriptor
    internal_static_robert_server_crypto_GenerateEBIDRequest_descriptor;
    public static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internal_static_robert_server_crypto_GenerateEBIDRequest_fieldAccessorTable;
    public static final com.google.protobuf.Descriptors.Descriptor
    internal_static_robert_server_crypto_EBIDResponse_descriptor;
    public static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internal_static_robert_server_crypto_EBIDResponse_fieldAccessorTable;
    public static final com.google.protobuf.Descriptors.Descriptor
    internal_static_robert_server_crypto_DecryptEBIDRequest_descriptor;
    public static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internal_static_robert_server_crypto_DecryptEBIDRequest_fieldAccessorTable;
    public static final com.google.protobuf.Descriptors.Descriptor
    internal_static_robert_server_crypto_EncryptCountryCodeRequest_descriptor;
    public static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internal_static_robert_server_crypto_EncryptCountryCodeRequest_fieldAccessorTable;
    public static final com.google.protobuf.Descriptors.Descriptor
    internal_static_robert_server_crypto_EncryptCountryCodeResponse_descriptor;
    public static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internal_static_robert_server_crypto_EncryptCountryCodeResponse_fieldAccessorTable;
    public static final com.google.protobuf.Descriptors.Descriptor
    internal_static_robert_server_crypto_DecryptCountryCodeRequest_descriptor;
    public static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internal_static_robert_server_crypto_DecryptCountryCodeRequest_fieldAccessorTable;
    public static final com.google.protobuf.Descriptors.Descriptor
    internal_static_robert_server_crypto_DecryptCountryCodeResponse_descriptor;
    public static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internal_static_robert_server_crypto_DecryptCountryCodeResponse_fieldAccessorTable;
    public static final com.google.protobuf.Descriptors.Descriptor
    internal_static_robert_server_crypto_MacHelloGenerationRequest_descriptor;
    public static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internal_static_robert_server_crypto_MacHelloGenerationRequest_fieldAccessorTable;
    public static final com.google.protobuf.Descriptors.Descriptor
    internal_static_robert_server_crypto_MacHelloGenerationResponse_descriptor;
    public static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internal_static_robert_server_crypto_MacHelloGenerationResponse_fieldAccessorTable;
    public static final com.google.protobuf.Descriptors.Descriptor
    internal_static_robert_server_crypto_MacHelloValidationRequest_descriptor;
    public static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internal_static_robert_server_crypto_MacHelloValidationRequest_fieldAccessorTable;
    public static final com.google.protobuf.Descriptors.Descriptor
    internal_static_robert_server_crypto_MacValidationResponse_descriptor;
    public static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internal_static_robert_server_crypto_MacValidationResponse_fieldAccessorTable;
    public static final com.google.protobuf.Descriptors.Descriptor
    internal_static_robert_server_crypto_MacEsrValidationRequest_descriptor;
    public static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internal_static_robert_server_crypto_MacEsrValidationRequest_fieldAccessorTable;
    public static final com.google.protobuf.Descriptors.Descriptor
    internal_static_robert_server_crypto_MacValidationForTypeRequest_descriptor;
    public static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internal_static_robert_server_crypto_MacValidationForTypeRequest_fieldAccessorTable;
    public static final com.google.protobuf.Descriptors.Descriptor
    internal_static_robert_server_crypto_GenerateIdentityRequest_descriptor;
    public static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internal_static_robert_server_crypto_GenerateIdentityRequest_fieldAccessorTable;
    public static final com.google.protobuf.Descriptors.Descriptor
    internal_static_robert_server_crypto_GenerateIdentityResponse_descriptor;
    public static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internal_static_robert_server_crypto_GenerateIdentityResponse_fieldAccessorTable;
    public static final com.google.protobuf.Descriptors.Descriptor
    internal_static_robert_server_crypto_EncryptedEphemeralTupleRequest_descriptor;
    public static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internal_static_robert_server_crypto_EncryptedEphemeralTupleRequest_fieldAccessorTable;
    public static final com.google.protobuf.Descriptors.Descriptor
    internal_static_robert_server_crypto_EncryptedEphemeralTupleResponse_descriptor;
    public static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internal_static_robert_server_crypto_EncryptedEphemeralTupleResponse_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }
    private static  com.google.protobuf.Descriptors.FileDescriptor
    descriptor;
    static {
        java.lang.String[] descriptorData = {
                "\n\024crypto_service.proto\022\024robert.server.cr" +
                        "ypto\"s\n\025EphemeralTupleRequest\022\013\n\003idA\030\001 \001" +
                        "(\014\022\026\n\016currentEpochID\030\002 \001(\005\022 \n\030numberOfEp" +
                        "ochsToGenerate\030\003 \001(\005\022\023\n\013countryCode\030\004 \001(" +
                        "\014\"D\n\026EphemeralTupleResponse\022\017\n\007epochId\030\001" +
                        " \001(\005\022\014\n\004ebid\030\002 \001(\014\022\013\n\003ecc\030\003 \001(\014\"3\n\023Gener" +
                        "ateEBIDRequest\022\013\n\003idA\030\001 \001(\014\022\017\n\007epochId\030\002" +
                        " \001(\005\"\034\n\014EBIDResponse\022\014\n\004ebid\030\001 \001(\014\"\"\n\022De" +
                        "cryptEBIDRequest\022\014\n\004ebid\030\001 \001(\014\">\n\031Encryp" +
                        "tCountryCodeRequest\022\014\n\004ebid\030\001 \001(\014\022\023\n\013cou" +
                        "ntryCode\030\002 \001(\014\":\n\032EncryptCountryCodeResp" +
                        "onse\022\034\n\024encryptedCountryCode\030\001 \001(\014\"G\n\031De" +
                        "cryptCountryCodeRequest\022\014\n\004ebid\030\001 \001(\014\022\034\n" +
                        "\024encryptedCountryCode\030\002 \001(\014\"1\n\032DecryptCo" +
                        "untryCodeResponse\022\023\n\013countryCode\030\001 \001(\014\"=" +
                        "\n\031MacHelloGenerationRequest\022\n\n\002ka\030\001 \001(\014\022" +
                        "\024\n\014helloMessage\030\002 \001(\014\"5\n\032MacHelloGenerat" +
                        "ionResponse\022\027\n\017macHelloMessage\030\001 \001(\014\"?\n\031" +
                        "MacHelloValidationRequest\022\n\n\002ka\030\001 \001(\014\022\026\n" +
                        "\016dataToValidate\030\002 \001(\014\"(\n\025MacValidationRe" +
                        "sponse\022\017\n\007isValid\030\001 \001(\010\"U\n\027MacEsrValidat" +
                        "ionRequest\022\n\n\002ka\030\001 \001(\014\022\026\n\016dataToValidate" +
                        "\030\002 \001(\014\022\026\n\016macToMatchWith\030\003 \001(\014\"j\n\033MacVal" +
                        "idationForTypeRequest\022\n\n\002ka\030\001 \001(\014\022\026\n\016dat" +
                        "aToValidate\030\002 \001(\014\022\026\n\016macToMatchWith\030\003 \001(" +
                        "\014\022\017\n\007prefixe\030\004 \001(\014\"2\n\027GenerateIdentityRe" +
                        "quest\022\027\n\017clientPublicKey\030\001 \001(\014\"b\n\030Genera" +
                        "teIdentityResponse\022\013\n\003idA\030\001 \001(\014\022\032\n\022encry" +
                        "ptedSharedKey\030\002 \001(\014\022\035\n\025serverPublicKeyFo" +
                        "rKey\030\003 \001(\014\"\225\001\n\036EncryptedEphemeralTupleRe" +
                        "quest\022\013\n\003idA\030\001 \001(\014\022\026\n\016currentEpochID\030\002 \001" +
                        "(\005\022 \n\030numberOfEpochsToGenerate\030\003 \001(\005\022\023\n\013" +
                        "countryCode\030\004 \001(\014\022\027\n\017clientPublicKey\030\005 \001" +
                        "(\014\"R\n\037EncryptedEphemeralTupleResponse\022\016\n" +
                        "\006tuples\030\001 \001(\014\022\037\n\027serverPublicKeyForTuple" +
                        "\030\003 \001(\0142\243\n\n\025CryptoGrpcServiceImpl\022w\n\026gene" +
                        "rateEphemeralTuple\022+.robert.server.crypt" +
                        "o.EphemeralTupleRequest\032,.robert.server." +
                        "crypto.EphemeralTupleResponse\"\0000\001\022_\n\014gen" +
                        "erateEBID\022).robert.server.crypto.Generat" +
                        "eEBIDRequest\032\".robert.server.crypto.EBID" +
                        "Response\"\000\022]\n\013decryptEBID\022(.robert.serve" +
                        "r.crypto.DecryptEBIDRequest\032\".robert.ser" +
                        "ver.crypto.EBIDResponse\"\000\022y\n\022encryptCoun" +
                        "tryCode\022/.robert.server.crypto.EncryptCo" +
                        "untryCodeRequest\0320.robert.server.crypto." +
                        "EncryptCountryCodeResponse\"\000\022y\n\022decryptC" +
                        "ountryCode\022/.robert.server.crypto.Decryp" +
                        "tCountryCodeRequest\0320.robert.server.cryp" +
                        "to.DecryptCountryCodeResponse\"\000\022w\n\020gener" +
                        "ateMacHello\022/.robert.server.crypto.MacHe" +
                        "lloGenerationRequest\0320.robert.server.cry" +
                        "pto.MacHelloGenerationResponse\"\000\022r\n\020vali" +
                        "dateMacHello\022/.robert.server.crypto.MacH" +
                        "elloValidationRequest\032+.robert.server.cr" +
                        "ypto.MacValidationResponse\"\000\022n\n\016validate" +
                        "MacEsr\022-.robert.server.crypto.MacEsrVali" +
                        "dationRequest\032+.robert.server.crypto.Mac" +
                        "ValidationResponse\"\000\022v\n\022validateMacForTy" +
                        "pe\0221.robert.server.crypto.MacValidationF" +
                        "orTypeRequest\032+.robert.server.crypto.Mac" +
                        "ValidationResponse\"\000\022s\n\020generateIdentity" +
                        "\022-.robert.server.crypto.GenerateIdentity" +
                        "Request\032..robert.server.crypto.GenerateI" +
                        "dentityResponse\"\000\022\220\001\n\037generateEncryptedE" +
                        "phemeralTuple\0224.robert.server.crypto.Enc" +
                        "ryptedEphemeralTupleRequest\0325.robert.ser" +
                        "ver.crypto.EncryptedEphemeralTupleRespon" +
                        "se\"\000BP\n6fr.gouv.stopc.robert.crypto.grpc" +
                        ".server.service.othersB\021CryptoGrpcServic" +
                        "eP\001\242\002\000b\006proto3"
        };
        descriptor = com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[] {
                });
        internal_static_robert_server_crypto_EphemeralTupleRequest_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_robert_server_crypto_EphemeralTupleRequest_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                        internal_static_robert_server_crypto_EphemeralTupleRequest_descriptor,
                        new java.lang.String[] { "IdA", "CurrentEpochID", "NumberOfEpochsToGenerate", "CountryCode", });
        internal_static_robert_server_crypto_EphemeralTupleResponse_descriptor =
                getDescriptor().getMessageTypes().get(1);
        internal_static_robert_server_crypto_EphemeralTupleResponse_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                        internal_static_robert_server_crypto_EphemeralTupleResponse_descriptor,
                        new java.lang.String[] { "EpochId", "Ebid", "Ecc", });
        internal_static_robert_server_crypto_GenerateEBIDRequest_descriptor =
                getDescriptor().getMessageTypes().get(2);
        internal_static_robert_server_crypto_GenerateEBIDRequest_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                        internal_static_robert_server_crypto_GenerateEBIDRequest_descriptor,
                        new java.lang.String[] { "IdA", "EpochId", });
        internal_static_robert_server_crypto_EBIDResponse_descriptor =
                getDescriptor().getMessageTypes().get(3);
        internal_static_robert_server_crypto_EBIDResponse_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                        internal_static_robert_server_crypto_EBIDResponse_descriptor,
                        new java.lang.String[] { "Ebid", });
        internal_static_robert_server_crypto_DecryptEBIDRequest_descriptor =
                getDescriptor().getMessageTypes().get(4);
        internal_static_robert_server_crypto_DecryptEBIDRequest_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                        internal_static_robert_server_crypto_DecryptEBIDRequest_descriptor,
                        new java.lang.String[] { "Ebid", });
        internal_static_robert_server_crypto_EncryptCountryCodeRequest_descriptor =
                getDescriptor().getMessageTypes().get(5);
        internal_static_robert_server_crypto_EncryptCountryCodeRequest_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                        internal_static_robert_server_crypto_EncryptCountryCodeRequest_descriptor,
                        new java.lang.String[] { "Ebid", "CountryCode", });
        internal_static_robert_server_crypto_EncryptCountryCodeResponse_descriptor =
                getDescriptor().getMessageTypes().get(6);
        internal_static_robert_server_crypto_EncryptCountryCodeResponse_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                        internal_static_robert_server_crypto_EncryptCountryCodeResponse_descriptor,
                        new java.lang.String[] { "EncryptedCountryCode", });
        internal_static_robert_server_crypto_DecryptCountryCodeRequest_descriptor =
                getDescriptor().getMessageTypes().get(7);
        internal_static_robert_server_crypto_DecryptCountryCodeRequest_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                        internal_static_robert_server_crypto_DecryptCountryCodeRequest_descriptor,
                        new java.lang.String[] { "Ebid", "EncryptedCountryCode", });
        internal_static_robert_server_crypto_DecryptCountryCodeResponse_descriptor =
                getDescriptor().getMessageTypes().get(8);
        internal_static_robert_server_crypto_DecryptCountryCodeResponse_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                        internal_static_robert_server_crypto_DecryptCountryCodeResponse_descriptor,
                        new java.lang.String[] { "CountryCode", });
        internal_static_robert_server_crypto_MacHelloGenerationRequest_descriptor =
                getDescriptor().getMessageTypes().get(9);
        internal_static_robert_server_crypto_MacHelloGenerationRequest_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                        internal_static_robert_server_crypto_MacHelloGenerationRequest_descriptor,
                        new java.lang.String[] { "Ka", "HelloMessage", });
        internal_static_robert_server_crypto_MacHelloGenerationResponse_descriptor =
                getDescriptor().getMessageTypes().get(10);
        internal_static_robert_server_crypto_MacHelloGenerationResponse_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                        internal_static_robert_server_crypto_MacHelloGenerationResponse_descriptor,
                        new java.lang.String[] { "MacHelloMessage", });
        internal_static_robert_server_crypto_MacHelloValidationRequest_descriptor =
                getDescriptor().getMessageTypes().get(11);
        internal_static_robert_server_crypto_MacHelloValidationRequest_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                        internal_static_robert_server_crypto_MacHelloValidationRequest_descriptor,
                        new java.lang.String[] { "Ka", "DataToValidate", });
        internal_static_robert_server_crypto_MacValidationResponse_descriptor =
                getDescriptor().getMessageTypes().get(12);
        internal_static_robert_server_crypto_MacValidationResponse_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                        internal_static_robert_server_crypto_MacValidationResponse_descriptor,
                        new java.lang.String[] { "IsValid", });
        internal_static_robert_server_crypto_MacEsrValidationRequest_descriptor =
                getDescriptor().getMessageTypes().get(13);
        internal_static_robert_server_crypto_MacEsrValidationRequest_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                        internal_static_robert_server_crypto_MacEsrValidationRequest_descriptor,
                        new java.lang.String[] { "Ka", "DataToValidate", "MacToMatchWith", });
        internal_static_robert_server_crypto_MacValidationForTypeRequest_descriptor =
                getDescriptor().getMessageTypes().get(14);
        internal_static_robert_server_crypto_MacValidationForTypeRequest_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                        internal_static_robert_server_crypto_MacValidationForTypeRequest_descriptor,
                        new java.lang.String[] { "Ka", "DataToValidate", "MacToMatchWith", "Prefixe", });
        internal_static_robert_server_crypto_GenerateIdentityRequest_descriptor =
                getDescriptor().getMessageTypes().get(15);
        internal_static_robert_server_crypto_GenerateIdentityRequest_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                        internal_static_robert_server_crypto_GenerateIdentityRequest_descriptor,
                        new java.lang.String[] { "ClientPublicKey", });
        internal_static_robert_server_crypto_GenerateIdentityResponse_descriptor =
                getDescriptor().getMessageTypes().get(16);
        internal_static_robert_server_crypto_GenerateIdentityResponse_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                        internal_static_robert_server_crypto_GenerateIdentityResponse_descriptor,
                        new java.lang.String[] { "IdA", "EncryptedSharedKey", "ServerPublicKeyForKey", });
        internal_static_robert_server_crypto_EncryptedEphemeralTupleRequest_descriptor =
                getDescriptor().getMessageTypes().get(17);
        internal_static_robert_server_crypto_EncryptedEphemeralTupleRequest_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                        internal_static_robert_server_crypto_EncryptedEphemeralTupleRequest_descriptor,
                        new java.lang.String[] { "IdA", "CurrentEpochID", "NumberOfEpochsToGenerate", "CountryCode", "ClientPublicKey", });
        internal_static_robert_server_crypto_EncryptedEphemeralTupleResponse_descriptor =
                getDescriptor().getMessageTypes().get(18);
        internal_static_robert_server_crypto_EncryptedEphemeralTupleResponse_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                        internal_static_robert_server_crypto_EncryptedEphemeralTupleResponse_descriptor,
                        new java.lang.String[] { "Tuples", "ServerPublicKeyForTuple", });
    }

    // @@protoc_insertion_point(outer_class_scope)
}
