// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: crypto_service.proto

package fr.gouv.stopc.robert.crypto.grpc.server.response;

public interface DecryptCountryCodeResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:robert.server.crypto.DecryptCountryCodeResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * byte[] countryCode;
   * </pre>
   *
   * <code>bytes countryCode = 1;</code>
   * @return The countryCode.
   */
  com.google.protobuf.ByteString getCountryCode();
}
