// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: crypto_service.proto

package fr.gouv.stopc.robert.crypto.grpc.server.response;

public interface EncryptCountryCodeResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:robert.server.crypto.EncryptCountryCodeResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * byte[] encryptedCountryCode;
   * </pre>
   *
   * <code>bytes encryptedCountryCode = 1;</code>
   * @return The encryptedCountryCode.
   */
  com.google.protobuf.ByteString getEncryptedCountryCode();
}
