// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: crypto_service.proto

package fr.gouv.stopc.robert.crypto.grpc.server.response;

import fr.gouv.stopc.robert.crypto.grpc.server.service.CryptoGrpcService;

/**
 * <pre>
 * The response message containing the greetings
 * </pre>
 *
 * Protobuf type {@code robert.server.crypto.EphemeralTupleResponse}
 */
public  final class EphemeralTupleResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:robert.server.crypto.EphemeralTupleResponse)
    EphemeralTupleResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use EphemeralTupleResponse.newBuilder() to construct.
  private EphemeralTupleResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private EphemeralTupleResponse() {
    ebid_ = com.google.protobuf.ByteString.EMPTY;
    ecc_ = com.google.protobuf.ByteString.EMPTY;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new EphemeralTupleResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private EphemeralTupleResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            epochId_ = input.readInt32();
            break;
          }
          case 18: {

            ebid_ = input.readBytes();
            break;
          }
          case 26: {

            ecc_ = input.readBytes();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return CryptoGrpcService.internal_static_robert_server_crypto_EphemeralTupleResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return CryptoGrpcService.internal_static_robert_server_crypto_EphemeralTupleResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            EphemeralTupleResponse.class, EphemeralTupleResponse.Builder.class);
  }

  public static final int EPOCHID_FIELD_NUMBER = 1;
  private int epochId_;
  /**
   * <pre>
   * int epochId;
   * byte[] ebid;
   * byte[] ecc;
   * </pre>
   *
   * <code>int32 epochId = 1;</code>
   * @return The epochId.
   */
  @Override
public int getEpochId() {
    return epochId_;
  }

  public static final int EBID_FIELD_NUMBER = 2;
  private com.google.protobuf.ByteString ebid_;
  /**
   * <code>bytes ebid = 2;</code>
   * @return The ebid.
   */
  @Override
public com.google.protobuf.ByteString getEbid() {
    return ebid_;
  }

  public static final int ECC_FIELD_NUMBER = 3;
  private com.google.protobuf.ByteString ecc_;
  /**
   * <code>bytes ecc = 3;</code>
   * @return The ecc.
   */
  @Override
public com.google.protobuf.ByteString getEcc() {
    return ecc_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (epochId_ != 0) {
      output.writeInt32(1, epochId_);
    }
    if (!ebid_.isEmpty()) {
      output.writeBytes(2, ebid_);
    }
    if (!ecc_.isEmpty()) {
      output.writeBytes(3, ecc_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (epochId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, epochId_);
    }
    if (!ebid_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(2, ebid_);
    }
    if (!ecc_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(3, ecc_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof EphemeralTupleResponse)) {
      return super.equals(obj);
    }
    EphemeralTupleResponse other = (EphemeralTupleResponse) obj;

    if (getEpochId()
        != other.getEpochId()) return false;
    if (!getEbid()
        .equals(other.getEbid())) return false;
    if (!getEcc()
        .equals(other.getEcc())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + EPOCHID_FIELD_NUMBER;
    hash = (53 * hash) + getEpochId();
    hash = (37 * hash) + EBID_FIELD_NUMBER;
    hash = (53 * hash) + getEbid().hashCode();
    hash = (37 * hash) + ECC_FIELD_NUMBER;
    hash = (53 * hash) + getEcc().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static EphemeralTupleResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static EphemeralTupleResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static EphemeralTupleResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static EphemeralTupleResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static EphemeralTupleResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static EphemeralTupleResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static EphemeralTupleResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static EphemeralTupleResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static EphemeralTupleResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static EphemeralTupleResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static EphemeralTupleResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static EphemeralTupleResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(EphemeralTupleResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * The response message containing the greetings
   * </pre>
   *
   * Protobuf type {@code robert.server.crypto.EphemeralTupleResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:robert.server.crypto.EphemeralTupleResponse)
      EphemeralTupleResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return CryptoGrpcService.internal_static_robert_server_crypto_EphemeralTupleResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return CryptoGrpcService.internal_static_robert_server_crypto_EphemeralTupleResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              EphemeralTupleResponse.class, EphemeralTupleResponse.Builder.class);
    }

    // Construct using EphemeralTupleResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      epochId_ = 0;

      ebid_ = com.google.protobuf.ByteString.EMPTY;

      ecc_ = com.google.protobuf.ByteString.EMPTY;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return CryptoGrpcService.internal_static_robert_server_crypto_EphemeralTupleResponse_descriptor;
    }

    @java.lang.Override
    public EphemeralTupleResponse getDefaultInstanceForType() {
      return EphemeralTupleResponse.getDefaultInstance();
    }

    @java.lang.Override
    public EphemeralTupleResponse build() {
      EphemeralTupleResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public EphemeralTupleResponse buildPartial() {
      EphemeralTupleResponse result = new EphemeralTupleResponse(this);
      result.epochId_ = epochId_;
      result.ebid_ = ebid_;
      result.ecc_ = ecc_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof EphemeralTupleResponse) {
        return mergeFrom((EphemeralTupleResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(EphemeralTupleResponse other) {
      if (other == EphemeralTupleResponse.getDefaultInstance()) return this;
      if (other.getEpochId() != 0) {
        setEpochId(other.getEpochId());
      }
      if (other.getEbid() != com.google.protobuf.ByteString.EMPTY) {
        setEbid(other.getEbid());
      }
      if (other.getEcc() != com.google.protobuf.ByteString.EMPTY) {
        setEcc(other.getEcc());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      EphemeralTupleResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (EphemeralTupleResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int epochId_ ;
    /**
     * <pre>
     * int epochId;
     * byte[] ebid;
     * byte[] ecc;
     * </pre>
     *
     * <code>int32 epochId = 1;</code>
     * @return The epochId.
     */
    @Override
	public int getEpochId() {
      return epochId_;
    }
    /**
     * <pre>
     * int epochId;
     * byte[] ebid;
     * byte[] ecc;
     * </pre>
     *
     * <code>int32 epochId = 1;</code>
     * @param value The epochId to set.
     * @return This builder for chaining.
     */
    public Builder setEpochId(int value) {
      
      epochId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * int epochId;
     * byte[] ebid;
     * byte[] ecc;
     * </pre>
     *
     * <code>int32 epochId = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearEpochId() {
      
      epochId_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString ebid_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes ebid = 2;</code>
     * @return The ebid.
     */
    @Override
	public com.google.protobuf.ByteString getEbid() {
      return ebid_;
    }
    /**
     * <code>bytes ebid = 2;</code>
     * @param value The ebid to set.
     * @return This builder for chaining.
     */
    public Builder setEbid(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      ebid_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bytes ebid = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearEbid() {
      
      ebid_ = getDefaultInstance().getEbid();
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString ecc_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes ecc = 3;</code>
     * @return The ecc.
     */
    @Override
	public com.google.protobuf.ByteString getEcc() {
      return ecc_;
    }
    /**
     * <code>bytes ecc = 3;</code>
     * @param value The ecc to set.
     * @return This builder for chaining.
     */
    public Builder setEcc(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      ecc_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bytes ecc = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearEcc() {
      
      ecc_ = getDefaultInstance().getEcc();
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:robert.server.crypto.EphemeralTupleResponse)
  }

  // @@protoc_insertion_point(class_scope:robert.server.crypto.EphemeralTupleResponse)
  private static final EphemeralTupleResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new EphemeralTupleResponse();
  }

  public static EphemeralTupleResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<EphemeralTupleResponse>
      PARSER = new com.google.protobuf.AbstractParser<EphemeralTupleResponse>() {
    @java.lang.Override
    public EphemeralTupleResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new EphemeralTupleResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<EphemeralTupleResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<EphemeralTupleResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public EphemeralTupleResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

