// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: crypto_service.proto

package fr.gouv.stopc.robert.crypto.grpc.server.response;

public interface EphemeralTupleResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:robert.server.crypto.EphemeralTupleResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * int epochId;
   * byte[] ebid;
   * byte[] ecc;
   * </pre>
   *
   * <code>int32 epochId = 1;</code>
   * @return The epochId.
   */
  int getEpochId();

  /**
   * <code>bytes ebid = 2;</code>
   * @return The ebid.
   */
  com.google.protobuf.ByteString getEbid();

  /**
   * <code>bytes ecc = 3;</code>
   * @return The ecc.
   */
  com.google.protobuf.ByteString getEcc();
}
