// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: crypto_service.proto

package fr.gouv.stopc.robert.crypto.grpc.server.response;

public interface GenerateIdentityResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:robert.server.crypto.GenerateIdentityResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes idA = 1;</code>
   * @return The idA.
   */
  com.google.protobuf.ByteString getIdA();

  /**
   * <code>bytes encryptedSharedKey = 2;</code>
   * @return The encryptedSharedKey.
   */
  com.google.protobuf.ByteString getEncryptedSharedKey();

  /**
   * <code>bytes serverPublicKeyForKey = 3;</code>
   * @return The serverPublicKeyForKey.
   */
  com.google.protobuf.ByteString getServerPublicKeyForKey();
}
