// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: crypto_service.proto

package fr.gouv.stopc.robert.crypto.grpc.server.response;

import fr.gouv.stopc.robert.crypto.grpc.server.service.CryptoGrpcService;

/**
 * Protobuf type {@code robert.server.crypto.MacHelloGenerationResponse}
 */
public  final class MacHelloGenerationResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:robert.server.crypto.MacHelloGenerationResponse)
    MacHelloGenerationResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use MacHelloGenerationResponse.newBuilder() to construct.
  private MacHelloGenerationResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private MacHelloGenerationResponse() {
    macHelloMessage_ = com.google.protobuf.ByteString.EMPTY;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new MacHelloGenerationResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private MacHelloGenerationResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {

            macHelloMessage_ = input.readBytes();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return CryptoGrpcService.internal_static_robert_server_crypto_MacHelloGenerationResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return CryptoGrpcService.internal_static_robert_server_crypto_MacHelloGenerationResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            MacHelloGenerationResponse.class, MacHelloGenerationResponse.Builder.class);
  }

  public static final int MACHELLOMESSAGE_FIELD_NUMBER = 1;
  private com.google.protobuf.ByteString macHelloMessage_;
  /**
   * <pre>
   * byte[] macHelloMessage;
   * </pre>
   *
   * <code>bytes macHelloMessage = 1;</code>
   * @return The macHelloMessage.
   */
  @Override
public com.google.protobuf.ByteString getMacHelloMessage() {
    return macHelloMessage_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!macHelloMessage_.isEmpty()) {
      output.writeBytes(1, macHelloMessage_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!macHelloMessage_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(1, macHelloMessage_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof MacHelloGenerationResponse)) {
      return super.equals(obj);
    }
    MacHelloGenerationResponse other = (MacHelloGenerationResponse) obj;

    if (!getMacHelloMessage()
        .equals(other.getMacHelloMessage())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + MACHELLOMESSAGE_FIELD_NUMBER;
    hash = (53 * hash) + getMacHelloMessage().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static MacHelloGenerationResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static MacHelloGenerationResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static MacHelloGenerationResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static MacHelloGenerationResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static MacHelloGenerationResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static MacHelloGenerationResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static MacHelloGenerationResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static MacHelloGenerationResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static MacHelloGenerationResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static MacHelloGenerationResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static MacHelloGenerationResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static MacHelloGenerationResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(MacHelloGenerationResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code robert.server.crypto.MacHelloGenerationResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:robert.server.crypto.MacHelloGenerationResponse)
      MacHelloGenerationResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return CryptoGrpcService.internal_static_robert_server_crypto_MacHelloGenerationResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return CryptoGrpcService.internal_static_robert_server_crypto_MacHelloGenerationResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              MacHelloGenerationResponse.class, MacHelloGenerationResponse.Builder.class);
    }

    // Construct using MacHelloGenerationResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      macHelloMessage_ = com.google.protobuf.ByteString.EMPTY;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return CryptoGrpcService.internal_static_robert_server_crypto_MacHelloGenerationResponse_descriptor;
    }

    @java.lang.Override
    public MacHelloGenerationResponse getDefaultInstanceForType() {
      return MacHelloGenerationResponse.getDefaultInstance();
    }

    @java.lang.Override
    public MacHelloGenerationResponse build() {
      MacHelloGenerationResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public MacHelloGenerationResponse buildPartial() {
      MacHelloGenerationResponse result = new MacHelloGenerationResponse(this);
      result.macHelloMessage_ = macHelloMessage_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof MacHelloGenerationResponse) {
        return mergeFrom((MacHelloGenerationResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(MacHelloGenerationResponse other) {
      if (other == MacHelloGenerationResponse.getDefaultInstance()) return this;
      if (other.getMacHelloMessage() != com.google.protobuf.ByteString.EMPTY) {
        setMacHelloMessage(other.getMacHelloMessage());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      MacHelloGenerationResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (MacHelloGenerationResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.google.protobuf.ByteString macHelloMessage_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <pre>
     * byte[] macHelloMessage;
     * </pre>
     *
     * <code>bytes macHelloMessage = 1;</code>
     * @return The macHelloMessage.
     */
    @Override
	public com.google.protobuf.ByteString getMacHelloMessage() {
      return macHelloMessage_;
    }
    /**
     * <pre>
     * byte[] macHelloMessage;
     * </pre>
     *
     * <code>bytes macHelloMessage = 1;</code>
     * @param value The macHelloMessage to set.
     * @return This builder for chaining.
     */
    public Builder setMacHelloMessage(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      macHelloMessage_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * byte[] macHelloMessage;
     * </pre>
     *
     * <code>bytes macHelloMessage = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearMacHelloMessage() {
      
      macHelloMessage_ = getDefaultInstance().getMacHelloMessage();
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:robert.server.crypto.MacHelloGenerationResponse)
  }

  // @@protoc_insertion_point(class_scope:robert.server.crypto.MacHelloGenerationResponse)
  private static final MacHelloGenerationResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new MacHelloGenerationResponse();
  }

  public static MacHelloGenerationResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MacHelloGenerationResponse>
      PARSER = new com.google.protobuf.AbstractParser<MacHelloGenerationResponse>() {
    @java.lang.Override
    public MacHelloGenerationResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new MacHelloGenerationResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<MacHelloGenerationResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<MacHelloGenerationResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public MacHelloGenerationResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

