// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: crypto_service.proto

package fr.gouv.stopc.robert.crypto.grpc.server.response;

public interface MacHelloGenerationResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:robert.server.crypto.MacHelloGenerationResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * byte[] macHelloMessage;
   * </pre>
   *
   * <code>bytes macHelloMessage = 1;</code>
   * @return The macHelloMessage.
   */
  com.google.protobuf.ByteString getMacHelloMessage();
}
