// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: crypto_service.proto

package fr.gouv.stopc.robert.crypto.grpc.server.response;

public interface MacValidationResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:robert.server.crypto.MacValidationResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * boolean isValid;
   * </pre>
   *
   * <code>bool isValid = 1;</code>
   * @return The isValid.
   */
  boolean getIsValid();
}
