// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: crypto_service.proto

package fr.gouv.stopc.robert.crypto.grpc.server.request;

public interface DecryptCountryCodeRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:robert.server.crypto.DecryptCountryCodeRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *  byte[] ebid;
   * byte encryptedCountryCode;
   * </pre>
   *
   * <code>bytes ebid = 1;</code>
   * @return The ebid.
   */
  com.google.protobuf.ByteString getEbid();

  /**
   * <code>bytes encryptedCountryCode = 2;</code>
   * @return The encryptedCountryCode.
   */
  com.google.protobuf.ByteString getEncryptedCountryCode();
}
