// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: crypto_service.proto

package fr.gouv.stopc.robert.crypto.grpc.server.request;

import fr.gouv.stopc.robert.crypto.grpc.server.service.CryptoGrpcService;

/**
 * Protobuf type {@code robert.server.crypto.DecryptCountryCodeRequest}
 */
public  final class DecryptCountryCodeRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:robert.server.crypto.DecryptCountryCodeRequest)
    DecryptCountryCodeRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use DecryptCountryCodeRequest.newBuilder() to construct.
  private DecryptCountryCodeRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private DecryptCountryCodeRequest() {
    ebid = com.google.protobuf.ByteString.EMPTY;
    encryptedCountryCode = com.google.protobuf.ByteString.EMPTY;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new DecryptCountryCodeRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private DecryptCountryCodeRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {

            ebid = input.readBytes();
            break;
          }
          case 18: {

            encryptedCountryCode = input.readBytes();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return CryptoGrpcService.internal_static_robert_server_crypto_DecryptCountryCodeRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return CryptoGrpcService.internal_static_robert_server_crypto_DecryptCountryCodeRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            DecryptCountryCodeRequest.class, DecryptCountryCodeRequest.Builder.class);
  }

  public static final int EBID_FIELD_NUMBER = 1;
  private com.google.protobuf.ByteString ebid;
  /**
   * <pre>
   *  byte[] ebid;
   * byte encryptedCountryCode;
   * </pre>
   *
   * <code>bytes ebid = 1;</code>
   * @return The ebid.
   */
  @Override
public com.google.protobuf.ByteString getEbid() {
    return ebid;
  }

  public static final int ENCRYPTEDCOUNTRYCODE_FIELD_NUMBER = 2;
  private com.google.protobuf.ByteString encryptedCountryCode;
  /**
   * <code>bytes encryptedCountryCode = 2;</code>
   * @return The encryptedCountryCode.
   */
  @Override
public com.google.protobuf.ByteString getEncryptedCountryCode() {
    return encryptedCountryCode;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!ebid.isEmpty()) {
      output.writeBytes(1, ebid);
    }
    if (!encryptedCountryCode.isEmpty()) {
      output.writeBytes(2, encryptedCountryCode);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!ebid.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(1, ebid);
    }
    if (!encryptedCountryCode.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(2, encryptedCountryCode);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof DecryptCountryCodeRequest)) {
      return super.equals(obj);
    }
    DecryptCountryCodeRequest other = (DecryptCountryCodeRequest) obj;

    if (!getEbid()
        .equals(other.getEbid())) return false;
    if (!getEncryptedCountryCode()
        .equals(other.getEncryptedCountryCode())) return false;
    
    return unknownFields.equals(other.unknownFields);
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + EBID_FIELD_NUMBER;
    hash = (53 * hash) + getEbid().hashCode();
    hash = (37 * hash) + ENCRYPTEDCOUNTRYCODE_FIELD_NUMBER;
    hash = (53 * hash) + getEncryptedCountryCode().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static DecryptCountryCodeRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static DecryptCountryCodeRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static DecryptCountryCodeRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static DecryptCountryCodeRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static DecryptCountryCodeRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static DecryptCountryCodeRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static DecryptCountryCodeRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static DecryptCountryCodeRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static DecryptCountryCodeRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static DecryptCountryCodeRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static DecryptCountryCodeRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static DecryptCountryCodeRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(DecryptCountryCodeRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    return new Builder(parent);
  }
  /**
   * Protobuf type {@code robert.server.crypto.DecryptCountryCodeRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:robert.server.crypto.DecryptCountryCodeRequest)
      DecryptCountryCodeRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return CryptoGrpcService.internal_static_robert_server_crypto_DecryptCountryCodeRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return CryptoGrpcService.internal_static_robert_server_crypto_DecryptCountryCodeRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              DecryptCountryCodeRequest.class, DecryptCountryCodeRequest.Builder.class);
    }

    // Construct using DecryptCountryCodeRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
    	// TODO : empty method, to fill or remove
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      ebid = com.google.protobuf.ByteString.EMPTY;

      encryptedCountryCode = com.google.protobuf.ByteString.EMPTY;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return CryptoGrpcService.internal_static_robert_server_crypto_DecryptCountryCodeRequest_descriptor;
    }

    @java.lang.Override
    public DecryptCountryCodeRequest getDefaultInstanceForType() {
      return DecryptCountryCodeRequest.getDefaultInstance();
    }

    @java.lang.Override
    public DecryptCountryCodeRequest build() {
      DecryptCountryCodeRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public DecryptCountryCodeRequest buildPartial() {
      DecryptCountryCodeRequest result = new DecryptCountryCodeRequest(this);
      result.ebid = ebid;
      result.encryptedCountryCode = encryptedCountryCode;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof DecryptCountryCodeRequest) {
        return mergeFrom((DecryptCountryCodeRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(DecryptCountryCodeRequest other) {
      if (other == DecryptCountryCodeRequest.getDefaultInstance()) return this;
      if (other.getEbid() != com.google.protobuf.ByteString.EMPTY) {
        setEbid(other.getEbid());
      }
      if (other.getEncryptedCountryCode() != com.google.protobuf.ByteString.EMPTY) {
        setEncryptedCountryCode(other.getEncryptedCountryCode());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      DecryptCountryCodeRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (DecryptCountryCodeRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.google.protobuf.ByteString ebid = com.google.protobuf.ByteString.EMPTY;
    /**
     * <pre>
     *  byte[] ebid;
     * byte encryptedCountryCode;
     * </pre>
     *
     * <code>bytes ebid = 1;</code>
     * @return The ebid.
     */
    @Override
	public com.google.protobuf.ByteString getEbid() {
      return ebid;
    }
    /**
     * <pre>
     *  byte[] ebid;
     * byte encryptedCountryCode;
     * </pre>
     *
     * <code>bytes ebid = 1;</code>
     * @param value The ebid to set.
     * @return This builder for chaining.
     */
    public Builder setEbid(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      ebid = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *  byte[] ebid;
     * byte encryptedCountryCode;
     * </pre>
     *
     * <code>bytes ebid = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearEbid() {
      
      ebid = getDefaultInstance().getEbid();
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString encryptedCountryCode = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes encryptedCountryCode = 2;</code>
     * @return The encryptedCountryCode.
     */
    @Override
	public com.google.protobuf.ByteString getEncryptedCountryCode() {
      return encryptedCountryCode;
    }
    /**
     * <code>bytes encryptedCountryCode = 2;</code>
     * @param value The encryptedCountryCode to set.
     * @return This builder for chaining.
     */
    public Builder setEncryptedCountryCode(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      encryptedCountryCode = value;
      onChanged();
      return this;
    }
    /**
     * <code>bytes encryptedCountryCode = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearEncryptedCountryCode() {
      
      encryptedCountryCode = getDefaultInstance().getEncryptedCountryCode();
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:robert.server.crypto.DecryptCountryCodeRequest)
  }

  // @@protoc_insertion_point(class_scope:robert.server.crypto.DecryptCountryCodeRequest)
  private static final DecryptCountryCodeRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new DecryptCountryCodeRequest();
  }

  public static DecryptCountryCodeRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<DecryptCountryCodeRequest>
      PARSER = new com.google.protobuf.AbstractParser<DecryptCountryCodeRequest>() {
    @java.lang.Override
    public DecryptCountryCodeRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new DecryptCountryCodeRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<DecryptCountryCodeRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<DecryptCountryCodeRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public DecryptCountryCodeRequest getDefaultInstanceForType() {
    return getDefaultInstance();
  }

}

