// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: crypto_service.proto

package fr.gouv.stopc.robert.crypto.grpc.server.request;

public interface DecryptEBIDRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:robert.server.crypto.DecryptEBIDRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes ebid = 1;</code>
   * @return The ebid.
   */
  com.google.protobuf.ByteString getEbid();
}
