// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: crypto_service.proto

package fr.gouv.stopc.robert.crypto.grpc.server.request;

public interface EncryptCountryCodeRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:robert.server.crypto.EncryptCountryCodeRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *  byte[] ebid;
   * byte countryCode;
   * </pre>
   *
   * <code>bytes ebid = 1;</code>
   * @return The ebid.
   */
  com.google.protobuf.ByteString getEbid();

  /**
   * <code>bytes countryCode = 2;</code>
   * @return The countryCode.
   */
  com.google.protobuf.ByteString getCountryCode();
}
