// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: crypto_service.proto

package fr.gouv.stopc.robert.crypto.grpc.server.request;

public interface EphemeralTupleRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:robert.server.crypto.EphemeralTupleRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes idA = 1;</code>
   * @return The idA.
   */
  com.google.protobuf.ByteString getIdA();

  /**
   * <code>int32 currentEpochID = 2;</code>
   * @return The currentEpochID.
   */
  int getCurrentEpochID();

  /**
   * <code>int32 numberOfEpochsToGenerate = 3;</code>
   * @return The numberOfEpochsToGenerate.
   */
  int getNumberOfEpochsToGenerate();

  /**
   * <code>bytes countryCode = 4;</code>
   * @return The countryCode.
   */
  com.google.protobuf.ByteString getCountryCode();
}
