// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: crypto_service.proto

package fr.gouv.stopc.robert.crypto.grpc.server.request;

import fr.gouv.stopc.robert.crypto.grpc.server.service.CryptoGrpcService;

/**
 * <pre>
 * The request message containing the user's name.
 * </pre>
 *
 * Protobuf type {@code robert.server.crypto.EphemeralTupleRequest}
 */
public  final class EphemeralTupleRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:robert.server.crypto.EphemeralTupleRequest)
    EphemeralTupleRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use EphemeralTupleRequest.newBuilder() to construct.
  private EphemeralTupleRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private EphemeralTupleRequest() {
    idA_ = com.google.protobuf.ByteString.EMPTY;
    countryCode_ = com.google.protobuf.ByteString.EMPTY;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new EphemeralTupleRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private EphemeralTupleRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {

            idA_ = input.readBytes();
            break;
          }
          case 16: {

            currentEpochID_ = input.readInt32();
            break;
          }
          case 24: {

            numberOfEpochsToGenerate_ = input.readInt32();
            break;
          }
          case 34: {

            countryCode_ = input.readBytes();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return CryptoGrpcService.internal_static_robert_server_crypto_EphemeralTupleRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return CryptoGrpcService.internal_static_robert_server_crypto_EphemeralTupleRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            EphemeralTupleRequest.class, EphemeralTupleRequest.Builder.class);
  }

  public static final int IDA_FIELD_NUMBER = 1;
  private com.google.protobuf.ByteString idA_;
  /**
   * <code>bytes idA = 1;</code>
   * @return The idA.
   */
  @Override
public com.google.protobuf.ByteString getIdA() {
    return idA_;
  }

  public static final int CURRENTEPOCHID_FIELD_NUMBER = 2;
  private int currentEpochID_;
  /**
   * <code>int32 currentEpochID = 2;</code>
   * @return The currentEpochID.
   */
  @Override
public int getCurrentEpochID() {
    return currentEpochID_;
  }

  public static final int NUMBEROFEPOCHSTOGENERATE_FIELD_NUMBER = 3;
  private int numberOfEpochsToGenerate_;
  /**
   * <code>int32 numberOfEpochsToGenerate = 3;</code>
   * @return The numberOfEpochsToGenerate.
   */
  @Override
public int getNumberOfEpochsToGenerate() {
    return numberOfEpochsToGenerate_;
  }

  public static final int COUNTRYCODE_FIELD_NUMBER = 4;
  private com.google.protobuf.ByteString countryCode_;
  /**
   * <code>bytes countryCode = 4;</code>
   * @return The countryCode.
   */
  @Override
public com.google.protobuf.ByteString getCountryCode() {
    return countryCode_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!idA_.isEmpty()) {
      output.writeBytes(1, idA_);
    }
    if (currentEpochID_ != 0) {
      output.writeInt32(2, currentEpochID_);
    }
    if (numberOfEpochsToGenerate_ != 0) {
      output.writeInt32(3, numberOfEpochsToGenerate_);
    }
    if (!countryCode_.isEmpty()) {
      output.writeBytes(4, countryCode_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!idA_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(1, idA_);
    }
    if (currentEpochID_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, currentEpochID_);
    }
    if (numberOfEpochsToGenerate_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, numberOfEpochsToGenerate_);
    }
    if (!countryCode_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(4, countryCode_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof EphemeralTupleRequest)) {
      return super.equals(obj);
    }
    EphemeralTupleRequest other = (EphemeralTupleRequest) obj;

    if (!getIdA()
        .equals(other.getIdA())) return false;
    if (getCurrentEpochID()
        != other.getCurrentEpochID()) return false;
    if (getNumberOfEpochsToGenerate()
        != other.getNumberOfEpochsToGenerate()) return false;
    if (!getCountryCode()
        .equals(other.getCountryCode())) return false;
    return unknownFields.equals(other.unknownFields);
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + IDA_FIELD_NUMBER;
    hash = (53 * hash) + getIdA().hashCode();
    hash = (37 * hash) + CURRENTEPOCHID_FIELD_NUMBER;
    hash = (53 * hash) + getCurrentEpochID();
    hash = (37 * hash) + NUMBEROFEPOCHSTOGENERATE_FIELD_NUMBER;
    hash = (53 * hash) + getNumberOfEpochsToGenerate();
    hash = (37 * hash) + COUNTRYCODE_FIELD_NUMBER;
    hash = (53 * hash) + getCountryCode().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static EphemeralTupleRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static EphemeralTupleRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static EphemeralTupleRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static EphemeralTupleRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static EphemeralTupleRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static EphemeralTupleRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static EphemeralTupleRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static EphemeralTupleRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static EphemeralTupleRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static EphemeralTupleRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static EphemeralTupleRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static EphemeralTupleRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(EphemeralTupleRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    return new Builder(parent);
  }
  /**
   * <pre>
   * The request message containing the user's name.
   * </pre>
   *
   * Protobuf type {@code robert.server.crypto.EphemeralTupleRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:robert.server.crypto.EphemeralTupleRequest)
      EphemeralTupleRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return CryptoGrpcService.internal_static_robert_server_crypto_EphemeralTupleRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return CryptoGrpcService.internal_static_robert_server_crypto_EphemeralTupleRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              EphemeralTupleRequest.class, EphemeralTupleRequest.Builder.class);
    }

    // Construct using EphemeralTupleRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      idA_ = com.google.protobuf.ByteString.EMPTY;

      currentEpochID_ = 0;

      numberOfEpochsToGenerate_ = 0;

      countryCode_ = com.google.protobuf.ByteString.EMPTY;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return CryptoGrpcService.internal_static_robert_server_crypto_EphemeralTupleRequest_descriptor;
    }

    @java.lang.Override
    public EphemeralTupleRequest getDefaultInstanceForType() {
      return EphemeralTupleRequest.getDefaultInstance();
    }

    @java.lang.Override
    public EphemeralTupleRequest build() {
      EphemeralTupleRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public EphemeralTupleRequest buildPartial() {
      EphemeralTupleRequest result = new EphemeralTupleRequest(this);
      result.idA_ = idA_;
      result.currentEpochID_ = currentEpochID_;
      result.numberOfEpochsToGenerate_ = numberOfEpochsToGenerate_;
      result.countryCode_ = countryCode_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof EphemeralTupleRequest) {
        return mergeFrom((EphemeralTupleRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(EphemeralTupleRequest other) {
      if (other == EphemeralTupleRequest.getDefaultInstance()) return this;
      if (other.getIdA() != com.google.protobuf.ByteString.EMPTY) {
        setIdA(other.getIdA());
      }
      if (other.getCurrentEpochID() != 0) {
        setCurrentEpochID(other.getCurrentEpochID());
      }
      if (other.getNumberOfEpochsToGenerate() != 0) {
        setNumberOfEpochsToGenerate(other.getNumberOfEpochsToGenerate());
      }
      if (other.getCountryCode() != com.google.protobuf.ByteString.EMPTY) {
        setCountryCode(other.getCountryCode());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      EphemeralTupleRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (EphemeralTupleRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.google.protobuf.ByteString idA_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes idA = 1;</code>
     * @return The idA.
     */
    @Override
	public com.google.protobuf.ByteString getIdA() {
      return idA_;
    }
    /**
     * <code>bytes idA = 1;</code>
     * @param value The idA to set.
     * @return This builder for chaining.
     */
    public Builder setIdA(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      idA_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bytes idA = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearIdA() {
      
      idA_ = getDefaultInstance().getIdA();
      onChanged();
      return this;
    }

    private int currentEpochID_ ;
    /**
     * <code>int32 currentEpochID = 2;</code>
     * @return The currentEpochID.
     */
    @Override
	public int getCurrentEpochID() {
      return currentEpochID_;
    }
    /**
     * <code>int32 currentEpochID = 2;</code>
     * @param value The currentEpochID to set.
     * @return This builder for chaining.
     */
    public Builder setCurrentEpochID(int value) {
      
      currentEpochID_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 currentEpochID = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearCurrentEpochID() {
      
      currentEpochID_ = 0;
      onChanged();
      return this;
    }

    private int numberOfEpochsToGenerate_ ;
    /**
     * <code>int32 numberOfEpochsToGenerate = 3;</code>
     * @return The numberOfEpochsToGenerate.
     */
    @Override
	public int getNumberOfEpochsToGenerate() {
      return numberOfEpochsToGenerate_;
    }
    /**
     * <code>int32 numberOfEpochsToGenerate = 3;</code>
     * @param value The numberOfEpochsToGenerate to set.
     * @return This builder for chaining.
     */
    public Builder setNumberOfEpochsToGenerate(int value) {
      
      numberOfEpochsToGenerate_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 numberOfEpochsToGenerate = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearNumberOfEpochsToGenerate() {
      
      numberOfEpochsToGenerate_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString countryCode_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes countryCode = 4;</code>
     * @return The countryCode.
     */
    @Override
	public com.google.protobuf.ByteString getCountryCode() {
      return countryCode_;
    }
    /**
     * <code>bytes countryCode = 4;</code>
     * @param value The countryCode to set.
     * @return This builder for chaining.
     */
    public Builder setCountryCode(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      countryCode_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bytes countryCode = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearCountryCode() {
      
      countryCode_ = getDefaultInstance().getCountryCode();
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:robert.server.crypto.EphemeralTupleRequest)
  }

  // @@protoc_insertion_point(class_scope:robert.server.crypto.EphemeralTupleRequest)
  private static final EphemeralTupleRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new EphemeralTupleRequest();
  }

  public static EphemeralTupleRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<EphemeralTupleRequest>
      PARSER = new com.google.protobuf.AbstractParser<EphemeralTupleRequest>() {
    @java.lang.Override
    public EphemeralTupleRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new EphemeralTupleRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<EphemeralTupleRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<EphemeralTupleRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public EphemeralTupleRequest getDefaultInstanceForType() {
    return getDefaultInstance();
  }

}

