// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: crypto_service.proto

package fr.gouv.stopc.robert.crypto.grpc.server.request;

public interface GenerateEBIDRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:robert.server.crypto.GenerateEBIDRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * byte[] IDA of Registration
   * int currentEpochID
   * </pre>
   *
   * <code>bytes idA = 1;</code>
   * @return The idA.
   */
  com.google.protobuf.ByteString getIdA();

  /**
   * <code>int32 epochId = 2;</code>
   * @return The epochId.
   */
  int getEpochId();
}
