// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: crypto_service.proto

package fr.gouv.stopc.robert.crypto.grpc.server.request;

import fr.gouv.stopc.robert.crypto.grpc.server.service.CryptoGrpcService;

/**
 * Protobuf type {@code robert.server.crypto.GenerateEBIDRequest}
 */
public  final class GenerateEBIDRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:robert.server.crypto.GenerateEBIDRequest)
    GenerateEBIDRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GenerateEBIDRequest.newBuilder() to construct.
  private GenerateEBIDRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GenerateEBIDRequest() {
    idA_ = com.google.protobuf.ByteString.EMPTY;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new GenerateEBIDRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GenerateEBIDRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {

            idA_ = input.readBytes();
            break;
          }
          case 16: {

            epochId_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return CryptoGrpcService.internal_static_robert_server_crypto_GenerateEBIDRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return CryptoGrpcService.internal_static_robert_server_crypto_GenerateEBIDRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            GenerateEBIDRequest.class, GenerateEBIDRequest.Builder.class);
  }

  public static final int IDA_FIELD_NUMBER = 1;
  private com.google.protobuf.ByteString idA_;
  /**
   * <pre>
   * byte[] IDA of Registration
   * int currentEpochID
   * </pre>
   *
   * <code>bytes idA = 1;</code>
   * @return The idA.
   */
  @Override
public com.google.protobuf.ByteString getIdA() {
    return idA_;
  }

  public static final int EPOCHID_FIELD_NUMBER = 2;
  private int epochId_;
  /**
   * <code>int32 epochId = 2;</code>
   * @return The epochId.
   */
  @Override
public int getEpochId() {
    return epochId_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!idA_.isEmpty()) {
      output.writeBytes(1, idA_);
    }
    if (epochId_ != 0) {
      output.writeInt32(2, epochId_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!idA_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(1, idA_);
    }
    if (epochId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, epochId_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof GenerateEBIDRequest)) {
      return super.equals(obj);
    }
    GenerateEBIDRequest other = (GenerateEBIDRequest) obj;

    if (!getIdA()
        .equals(other.getIdA())) return false;
    if (getEpochId()
        != other.getEpochId()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + IDA_FIELD_NUMBER;
    hash = (53 * hash) + getIdA().hashCode();
    hash = (37 * hash) + EPOCHID_FIELD_NUMBER;
    hash = (53 * hash) + getEpochId();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static GenerateEBIDRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static GenerateEBIDRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static GenerateEBIDRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static GenerateEBIDRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static GenerateEBIDRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static GenerateEBIDRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static GenerateEBIDRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static GenerateEBIDRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static GenerateEBIDRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static GenerateEBIDRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static GenerateEBIDRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static GenerateEBIDRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(GenerateEBIDRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code robert.server.crypto.GenerateEBIDRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:robert.server.crypto.GenerateEBIDRequest)
      GenerateEBIDRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return CryptoGrpcService.internal_static_robert_server_crypto_GenerateEBIDRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return CryptoGrpcService.internal_static_robert_server_crypto_GenerateEBIDRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              GenerateEBIDRequest.class, GenerateEBIDRequest.Builder.class);
    }

    // Construct using GenerateEBIDRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      idA_ = com.google.protobuf.ByteString.EMPTY;

      epochId_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return CryptoGrpcService.internal_static_robert_server_crypto_GenerateEBIDRequest_descriptor;
    }

    @java.lang.Override
    public GenerateEBIDRequest getDefaultInstanceForType() {
      return GenerateEBIDRequest.getDefaultInstance();
    }

    @java.lang.Override
    public GenerateEBIDRequest build() {
      GenerateEBIDRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public GenerateEBIDRequest buildPartial() {
      GenerateEBIDRequest result = new GenerateEBIDRequest(this);
      result.idA_ = idA_;
      result.epochId_ = epochId_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof GenerateEBIDRequest) {
        return mergeFrom((GenerateEBIDRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(GenerateEBIDRequest other) {
      if (other == GenerateEBIDRequest.getDefaultInstance()) return this;
      if (other.getIdA() != com.google.protobuf.ByteString.EMPTY) {
        setIdA(other.getIdA());
      }
      if (other.getEpochId() != 0) {
        setEpochId(other.getEpochId());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      GenerateEBIDRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (GenerateEBIDRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.google.protobuf.ByteString idA_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <pre>
     * byte[] IDA of Registration
     * int currentEpochID
     * </pre>
     *
     * <code>bytes idA = 1;</code>
     * @return The idA.
     */
    @Override
	public com.google.protobuf.ByteString getIdA() {
      return idA_;
    }
    /**
     * <pre>
     * byte[] IDA of Registration
     * int currentEpochID
     * </pre>
     *
     * <code>bytes idA = 1;</code>
     * @param value The idA to set.
     * @return This builder for chaining.
     */
    public Builder setIdA(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      idA_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * byte[] IDA of Registration
     * int currentEpochID
     * </pre>
     *
     * <code>bytes idA = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearIdA() {
      
      idA_ = getDefaultInstance().getIdA();
      onChanged();
      return this;
    }

    private int epochId_ ;
    /**
     * <code>int32 epochId = 2;</code>
     * @return The epochId.
     */
    @Override
	public int getEpochId() {
      return epochId_;
    }
    /**
     * <code>int32 epochId = 2;</code>
     * @param value The epochId to set.
     * @return This builder for chaining.
     */
    public Builder setEpochId(int value) {
      
      epochId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 epochId = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearEpochId() {
      
      epochId_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:robert.server.crypto.GenerateEBIDRequest)
  }

  // @@protoc_insertion_point(class_scope:robert.server.crypto.GenerateEBIDRequest)
  private static final GenerateEBIDRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new GenerateEBIDRequest();
  }

  public static GenerateEBIDRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GenerateEBIDRequest>
      PARSER = new com.google.protobuf.AbstractParser<GenerateEBIDRequest>() {
    @java.lang.Override
    public GenerateEBIDRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GenerateEBIDRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GenerateEBIDRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GenerateEBIDRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public GenerateEBIDRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

