// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: crypto_service.proto

package fr.gouv.stopc.robert.crypto.grpc.server.request;

public interface GenerateIdentityRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:robert.server.crypto.GenerateIdentityRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes clientPublicKey = 1;</code>
   * @return The clientPublicKey.
   */
  com.google.protobuf.ByteString getClientPublicKey();
}
