// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: crypto_service.proto

package fr.gouv.stopc.robert.crypto.grpc.server.request;

public interface MacEsrValidationRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:robert.server.crypto.MacEsrValidationRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * byte[] KA;
   * byte[] dataToValidate;
   * byte[] macToMatchWith;
   * </pre>
   *
   * <code>bytes ka = 1;</code>
   * @return The ka.
   */
  com.google.protobuf.ByteString getKa();

  /**
   * <code>bytes dataToValidate = 2;</code>
   * @return The dataToValidate.
   */
  com.google.protobuf.ByteString getDataToValidate();

  /**
   * <code>bytes macToMatchWith = 3;</code>
   * @return The macToMatchWith.
   */
  com.google.protobuf.ByteString getMacToMatchWith();
}
