// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: crypto_service.proto

package fr.gouv.stopc.robert.crypto.grpc.server.request;

public interface MacHelloValidationRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:robert.server.crypto.MacHelloValidationRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * byte[] KA;
   * byte[] dataToValidate;
   * </pre>
   *
   * <code>bytes ka = 1;</code>
   * @return The ka.
   */
  com.google.protobuf.ByteString getKa();

  /**
   * <code>bytes dataToValidate = 2;</code>
   * @return The dataToValidate.
   */
  com.google.protobuf.ByteString getDataToValidate();
}
