// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: crypto_service.proto

package fr.gouv.stopc.robert.crypto.grpc.server.request;

import fr.gouv.stopc.robert.crypto.grpc.server.service.CryptoGrpcService;

/**
 * Protobuf type {@code robert.server.crypto.MacValidationForTypeRequest}
 */
public  final class MacValidationForTypeRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:robert.server.crypto.MacValidationForTypeRequest)
    MacValidationForTypeRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use MacValidationForTypeRequest.newBuilder() to construct.
  private MacValidationForTypeRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private MacValidationForTypeRequest() {
    ka_ = com.google.protobuf.ByteString.EMPTY;
    dataToValidate_ = com.google.protobuf.ByteString.EMPTY;
    macToMatchWith_ = com.google.protobuf.ByteString.EMPTY;
    prefixe_ = com.google.protobuf.ByteString.EMPTY;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new MacValidationForTypeRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private MacValidationForTypeRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {

            ka_ = input.readBytes();
            break;
          }
          case 18: {

            dataToValidate_ = input.readBytes();
            break;
          }
          case 26: {

            macToMatchWith_ = input.readBytes();
            break;
          }
          case 34: {

            prefixe_ = input.readBytes();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return CryptoGrpcService.internal_static_robert_server_crypto_MacValidationForTypeRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return CryptoGrpcService.internal_static_robert_server_crypto_MacValidationForTypeRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            MacValidationForTypeRequest.class, MacValidationForTypeRequest.Builder.class);
  }

  public static final int KA_FIELD_NUMBER = 1;
  private com.google.protobuf.ByteString ka_;
  /**
   * <pre>
   * byte[] KA;
   * byte[] dataToValidate;
   * byte[] macToMatchWith;
   * byte prefixes;
   * </pre>
   *
   * <code>bytes ka = 1;</code>
   * @return The ka.
   */
  @Override
public com.google.protobuf.ByteString getKa() {
    return ka_;
  }

  public static final int DATATOVALIDATE_FIELD_NUMBER = 2;
  private com.google.protobuf.ByteString dataToValidate_;
  /**
   * <code>bytes dataToValidate = 2;</code>
   * @return The dataToValidate.
   */
  @Override
public com.google.protobuf.ByteString getDataToValidate() {
    return dataToValidate_;
  }

  public static final int MACTOMATCHWITH_FIELD_NUMBER = 3;
  private com.google.protobuf.ByteString macToMatchWith_;
  /**
   * <code>bytes macToMatchWith = 3;</code>
   * @return The macToMatchWith.
   */
  @Override
public com.google.protobuf.ByteString getMacToMatchWith() {
    return macToMatchWith_;
  }

  public static final int PREFIXE_FIELD_NUMBER = 4;
  private com.google.protobuf.ByteString prefixe_;
  /**
   * <code>bytes prefixe = 4;</code>
   * @return The prefixe.
   */
  @Override
public com.google.protobuf.ByteString getPrefixe() {
    return prefixe_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!ka_.isEmpty()) {
      output.writeBytes(1, ka_);
    }
    if (!dataToValidate_.isEmpty()) {
      output.writeBytes(2, dataToValidate_);
    }
    if (!macToMatchWith_.isEmpty()) {
      output.writeBytes(3, macToMatchWith_);
    }
    if (!prefixe_.isEmpty()) {
      output.writeBytes(4, prefixe_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!ka_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(1, ka_);
    }
    if (!dataToValidate_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(2, dataToValidate_);
    }
    if (!macToMatchWith_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(3, macToMatchWith_);
    }
    if (!prefixe_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(4, prefixe_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof MacValidationForTypeRequest)) {
      return super.equals(obj);
    }
    MacValidationForTypeRequest other = (MacValidationForTypeRequest) obj;

    if (!getKa()
        .equals(other.getKa())) return false;
    if (!getDataToValidate()
        .equals(other.getDataToValidate())) return false;
    if (!getMacToMatchWith()
        .equals(other.getMacToMatchWith())) return false;
    if (!getPrefixe()
        .equals(other.getPrefixe())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + KA_FIELD_NUMBER;
    hash = (53 * hash) + getKa().hashCode();
    hash = (37 * hash) + DATATOVALIDATE_FIELD_NUMBER;
    hash = (53 * hash) + getDataToValidate().hashCode();
    hash = (37 * hash) + MACTOMATCHWITH_FIELD_NUMBER;
    hash = (53 * hash) + getMacToMatchWith().hashCode();
    hash = (37 * hash) + PREFIXE_FIELD_NUMBER;
    hash = (53 * hash) + getPrefixe().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static MacValidationForTypeRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static MacValidationForTypeRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static MacValidationForTypeRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static MacValidationForTypeRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static MacValidationForTypeRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static MacValidationForTypeRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static MacValidationForTypeRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static MacValidationForTypeRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static MacValidationForTypeRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static MacValidationForTypeRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static MacValidationForTypeRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static MacValidationForTypeRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(MacValidationForTypeRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code robert.server.crypto.MacValidationForTypeRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:robert.server.crypto.MacValidationForTypeRequest)
      MacValidationForTypeRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return CryptoGrpcService.internal_static_robert_server_crypto_MacValidationForTypeRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return CryptoGrpcService.internal_static_robert_server_crypto_MacValidationForTypeRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              MacValidationForTypeRequest.class, MacValidationForTypeRequest.Builder.class);
    }

    // Construct using MacValidationForTypeRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      ka_ = com.google.protobuf.ByteString.EMPTY;

      dataToValidate_ = com.google.protobuf.ByteString.EMPTY;

      macToMatchWith_ = com.google.protobuf.ByteString.EMPTY;

      prefixe_ = com.google.protobuf.ByteString.EMPTY;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return CryptoGrpcService.internal_static_robert_server_crypto_MacValidationForTypeRequest_descriptor;
    }

    @java.lang.Override
    public MacValidationForTypeRequest getDefaultInstanceForType() {
      return MacValidationForTypeRequest.getDefaultInstance();
    }

    @java.lang.Override
    public MacValidationForTypeRequest build() {
      MacValidationForTypeRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public MacValidationForTypeRequest buildPartial() {
      MacValidationForTypeRequest result = new MacValidationForTypeRequest(this);
      result.ka_ = ka_;
      result.dataToValidate_ = dataToValidate_;
      result.macToMatchWith_ = macToMatchWith_;
      result.prefixe_ = prefixe_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof MacValidationForTypeRequest) {
        return mergeFrom((MacValidationForTypeRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(MacValidationForTypeRequest other) {
      if (other == MacValidationForTypeRequest.getDefaultInstance()) return this;
      if (other.getKa() != com.google.protobuf.ByteString.EMPTY) {
        setKa(other.getKa());
      }
      if (other.getDataToValidate() != com.google.protobuf.ByteString.EMPTY) {
        setDataToValidate(other.getDataToValidate());
      }
      if (other.getMacToMatchWith() != com.google.protobuf.ByteString.EMPTY) {
        setMacToMatchWith(other.getMacToMatchWith());
      }
      if (other.getPrefixe() != com.google.protobuf.ByteString.EMPTY) {
        setPrefixe(other.getPrefixe());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      MacValidationForTypeRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (MacValidationForTypeRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.google.protobuf.ByteString ka_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <pre>
     * byte[] KA;
     * byte[] dataToValidate;
     * byte[] macToMatchWith;
     * byte prefixes;
     * </pre>
     *
     * <code>bytes ka = 1;</code>
     * @return The ka.
     */
    @Override
	public com.google.protobuf.ByteString getKa() {
      return ka_;
    }
    /**
     * <pre>
     * byte[] KA;
     * byte[] dataToValidate;
     * byte[] macToMatchWith;
     * byte prefixes;
     * </pre>
     *
     * <code>bytes ka = 1;</code>
     * @param value The ka to set.
     * @return This builder for chaining.
     */
    public Builder setKa(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      ka_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * byte[] KA;
     * byte[] dataToValidate;
     * byte[] macToMatchWith;
     * byte prefixes;
     * </pre>
     *
     * <code>bytes ka = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearKa() {
      
      ka_ = getDefaultInstance().getKa();
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString dataToValidate_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes dataToValidate = 2;</code>
     * @return The dataToValidate.
     */
    @Override
	public com.google.protobuf.ByteString getDataToValidate() {
      return dataToValidate_;
    }
    /**
     * <code>bytes dataToValidate = 2;</code>
     * @param value The dataToValidate to set.
     * @return This builder for chaining.
     */
    public Builder setDataToValidate(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      dataToValidate_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bytes dataToValidate = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearDataToValidate() {
      
      dataToValidate_ = getDefaultInstance().getDataToValidate();
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString macToMatchWith_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes macToMatchWith = 3;</code>
     * @return The macToMatchWith.
     */
    @Override
	public com.google.protobuf.ByteString getMacToMatchWith() {
      return macToMatchWith_;
    }
    /**
     * <code>bytes macToMatchWith = 3;</code>
     * @param value The macToMatchWith to set.
     * @return This builder for chaining.
     */
    public Builder setMacToMatchWith(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      macToMatchWith_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bytes macToMatchWith = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearMacToMatchWith() {
      
      macToMatchWith_ = getDefaultInstance().getMacToMatchWith();
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString prefixe_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes prefixe = 4;</code>
     * @return The prefixe.
     */
    @Override
	public com.google.protobuf.ByteString getPrefixe() {
      return prefixe_;
    }
    /**
     * <code>bytes prefixe = 4;</code>
     * @param value The prefixe to set.
     * @return This builder for chaining.
     */
    public Builder setPrefixe(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      prefixe_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bytes prefixe = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearPrefixe() {
      
      prefixe_ = getDefaultInstance().getPrefixe();
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:robert.server.crypto.MacValidationForTypeRequest)
  }

  // @@protoc_insertion_point(class_scope:robert.server.crypto.MacValidationForTypeRequest)
  private static final MacValidationForTypeRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new MacValidationForTypeRequest();
  }

  public static MacValidationForTypeRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MacValidationForTypeRequest>
      PARSER = new com.google.protobuf.AbstractParser<MacValidationForTypeRequest>() {
    @java.lang.Override
    public MacValidationForTypeRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new MacValidationForTypeRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<MacValidationForTypeRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<MacValidationForTypeRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public MacValidationForTypeRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

